
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'~\x03n\x84E-D\x87\xe6\xb6!\xfe\x1d\xce\xb3\x1b'
    
_lr_action_items = {'CLASS':([0,2,6,29,30,36,37,],[3,3,3,-50,-51,-52,-49,]),'SYNCHRONIZATION':([25,38,39,52,53,75,85,],[41,-1,-36,-33,-34,-1,-35,]),'FLECHE':([88,89,],[-25,95,]),'END':([17,21,22,23,40,41,42,43,55,56,57,59,60,61,62,64,66,67,68,76,77,79,80,87,92,94,96,97,98,99,100,],[29,-47,-48,37,-1,-1,-1,-1,-45,-43,-1,-10,-11,-1,-13,-46,-1,-28,-30,-44,-42,-12,-29,-1,-6,-8,-5,-1,-24,-26,-7,]),'ANDCOMMERCIAL':([87,96,97,],[93,-5,93,]),'EVENT':([13,14,15,18,26,31,32,33,34,35,36,37,46,48,49,51,73,74,83,84,],[24,-19,28,-20,-21,-22,-23,-1,-15,-1,-52,-49,-40,-37,-16,-18,-1,-1,-41,-17,]),'DEUXPOINTS':([58,63,65,69,],[78,-9,-27,81,]),'TRANSITION':([27,44,45,70,72,82,90,],[43,-32,-1,-38,-31,-1,-39,]),'$end':([0,1,2,4,6,7,12,29,30,36,37,],[-1,-55,-1,0,-1,-54,-53,-50,-51,-52,-49,]),'IDENTIFIER':([3,5,8,9,10,11,14,16,18,19,20,24,28,34,35,36,37,41,43,47,49,50,51,54,59,61,66,71,74,78,81,84,87,91,92,93,94,95,96,97,98,99,100,],[9,11,16,-3,16,-4,16,-14,16,32,34,39,44,-15,-1,-52,-49,63,65,32,-16,34,-18,39,-10,63,65,44,-1,86,88,-17,-1,96,-6,86,-8,99,-5,-1,-24,-26,-7,]),'OBSERVER':([40,41,42,43,59,60,61,62,66,67,68,79,80,87,92,94,96,97,98,99,100,],[57,-1,57,-1,-10,-11,-1,-13,-1,-28,-30,-12,-29,-1,-6,-8,-5,-1,-24,-26,-7,]),'POINT':([86,],[91,]),'BLOCK':([0,2,6,8,9,10,11,14,18,29,30,34,35,36,37,49,51,74,84,],[5,5,5,5,-3,5,-4,5,5,-50,-51,-15,-1,-52,-49,-16,-18,-1,-17,]),'STATE':([8,9,10,11,],[19,-3,19,-4,]),'VIRGULE':([32,33,34,35,38,39,44,45,73,74,75,82,],[-23,47,-15,50,54,-36,-32,71,47,50,54,71,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ObserverStar':([57,],[76,]),'DestStateIdentifierInTransition':([95,],[98,]),'StateIdentifier':([19,47,],[33,73,]),'ObserverClauseQuestionMark':([40,42,],[55,64,]),'EventIdentifierInSynchronization':([41,61,],[58,58,]),'Model':([0,2,6,],[4,7,12,]),'Block':([0,2,6,8,10,14,18,],[6,6,6,14,14,14,14,]),'ComposedBlockClause':([8,10,14,18,],[13,13,26,31,]),'ClassInstanceIdentifier':([20,50,],[35,74,]),'StateClause':([8,10,],[15,15,]),'StateVirguleIdentifierStar':([33,73,],[48,83,]),'EndBlock':([23,],[36,]),'BlockIdentifier':([5,],[10,]),'Class':([0,2,6,],[2,2,2,]),'MacroEventDefinition':([41,61,],[59,59,]),'BlockBody':([8,10,],[17,23,]),'ClassInstance':([8,10,14,18,],[18,18,18,18,]),'TransitionClause':([27,],[42,]),'TransitionStar':([43,66,],[68,80,]),'EventClauseInClass':([15,],[27,]),'SynchronizationClause':([25,],[40,]),'OriginalStateIdentifierInTransition':([81,],[89,]),'ClassNameIdentifier':([8,10,14,18,],[20,20,20,20,]),'EventIdentifierInTransition':([43,66,],[69,69,]),'Synchronization':([41,61,],[61,61,]),'EventIdentifierInClass':([28,71,],[45,82,]),'BasicBlockBody':([8,10,],[21,21,]),'InternalBlockBody':([8,10,],[22,22,]),'EventVirguleIdentifierStarInBlock':([38,75,],[52,85,]),'EndClass':([17,],[30,]),'EventVirguleIdentifierStarInClass':([45,82,],[72,90,]),'ClassIdentifier':([3,],[8,]),'EventClauseInBlock':([13,],[25,]),'Transition':([43,66,],[66,66,]),'EventPath':([78,93,],[87,97,]),'empty':([0,2,6,33,35,38,40,41,42,43,45,57,61,66,73,74,75,82,87,97,],[1,1,1,46,49,53,56,60,56,67,70,77,60,67,46,49,53,70,92,92,]),'EventIdentifierInBlock':([24,54,],[38,75,]),'SynchronizationStar':([41,61,],[62,79,]),'AndCommercialEvenPathStar':([87,97,],[94,100,]),'ClassInstanceVirguleIdentifierStar':([35,74,],[51,84,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Model","S'",1,None,None,None),
  ('empty -> <empty>','empty',0,'p_empty','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',31),
  ('Identifier -> IDENTIFIER','Identifier',1,'p_Identifier','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',35),
  ('ClassIdentifier -> IDENTIFIER','ClassIdentifier',1,'p_ClassIdentifier','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',38),
  ('BlockIdentifier -> IDENTIFIER','BlockIdentifier',1,'p_BlockIdentifier','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',42),
  ('EventPath -> IDENTIFIER POINT IDENTIFIER','EventPath',3,'p_EventPath','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',60),
  ('AndCommercialEvenPathStar -> empty','AndCommercialEvenPathStar',1,'p_AndCommercialEvenPathStar','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',79),
  ('AndCommercialEvenPathStar -> ANDCOMMERCIAL EventPath AndCommercialEvenPathStar','AndCommercialEvenPathStar',3,'p_AndCommercialEvenPathStar','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',80),
  ('MacroEventDefinition -> EventIdentifierInSynchronization DEUXPOINTS EventPath AndCommercialEvenPathStar','MacroEventDefinition',4,'p_MacroEventDefinition','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',83),
  ('EventIdentifierInSynchronization -> IDENTIFIER','EventIdentifierInSynchronization',1,'p_EventIdentifierInSynchronization','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',92),
  ('Synchronization -> MacroEventDefinition','Synchronization',1,'p_Synchronization','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',96),
  ('SynchronizationStar -> empty','SynchronizationStar',1,'p_SynchronizationStar','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',99),
  ('SynchronizationStar -> Synchronization SynchronizationStar','SynchronizationStar',2,'p_SynchronizationStar','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',100),
  ('SynchronizationClause -> SYNCHRONIZATION SynchronizationStar','SynchronizationClause',2,'p_SynchronizationClause','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',103),
  ('ClassNameIdentifier -> IDENTIFIER','ClassNameIdentifier',1,'p_ClassNameIdentifier','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',106),
  ('ClassInstanceIdentifier -> IDENTIFIER','ClassInstanceIdentifier',1,'p_ClassInstanceIdentifier','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',110),
  ('ClassInstanceVirguleIdentifierStar -> empty','ClassInstanceVirguleIdentifierStar',1,'p_ClassInstanceVirguleIdentifierStar','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',114),
  ('ClassInstanceVirguleIdentifierStar -> VIRGULE ClassInstanceIdentifier ClassInstanceVirguleIdentifierStar','ClassInstanceVirguleIdentifierStar',3,'p_ClassInstanceVirguleIdentifierStar','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',115),
  ('ClassInstance -> ClassNameIdentifier ClassInstanceIdentifier ClassInstanceVirguleIdentifierStar','ClassInstance',3,'p_ClassInstance','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',119),
  ('ComposedBlockClause -> Block','ComposedBlockClause',1,'p_ComposedBlockClause','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',130),
  ('ComposedBlockClause -> ClassInstance','ComposedBlockClause',1,'p_ComposedBlockClause','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',131),
  ('ComposedBlockClause -> Block ComposedBlockClause','ComposedBlockClause',2,'p_ComposedBlockClause','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',132),
  ('ComposedBlockClause -> ClassInstance ComposedBlockClause','ComposedBlockClause',2,'p_ComposedBlockClause','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',133),
  ('StateIdentifier -> IDENTIFIER','StateIdentifier',1,'p_StateIdentifier','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',137),
  ('Transition -> EventIdentifierInTransition DEUXPOINTS OriginalStateIdentifierInTransition FLECHE DestStateIdentifierInTransition','Transition',5,'p_Transition','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',145),
  ('OriginalStateIdentifierInTransition -> IDENTIFIER','OriginalStateIdentifierInTransition',1,'p_OriginalStateIdentifierInTransition','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',148),
  ('DestStateIdentifierInTransition -> IDENTIFIER','DestStateIdentifierInTransition',1,'p_DestStateIdentifierInTransition','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',152),
  ('EventIdentifierInTransition -> IDENTIFIER','EventIdentifierInTransition',1,'p_EventIdentifierInTransition','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',156),
  ('TransitionStar -> empty','TransitionStar',1,'p_TransitionStar','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',160),
  ('TransitionStar -> Transition TransitionStar','TransitionStar',2,'p_TransitionStar','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',161),
  ('TransitionClause -> TRANSITION TransitionStar','TransitionClause',2,'p_TransitionClause','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',164),
  ('EventClauseInClass -> EVENT EventIdentifierInClass EventVirguleIdentifierStarInClass','EventClauseInClass',3,'p_EventClauseInClass','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',167),
  ('EventIdentifierInClass -> IDENTIFIER','EventIdentifierInClass',1,'p_EventIdentifierInClass','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',170),
  ('EventClauseInBlock -> EVENT EventIdentifierInBlock EventVirguleIdentifierStarInBlock','EventClauseInBlock',3,'p_EventClauseInBlock','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',174),
  ('EventVirguleIdentifierStarInBlock -> empty','EventVirguleIdentifierStarInBlock',1,'p_EventVirguleIdentifierStarInBlock','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',177),
  ('EventVirguleIdentifierStarInBlock -> VIRGULE EventIdentifierInBlock EventVirguleIdentifierStarInBlock','EventVirguleIdentifierStarInBlock',3,'p_EventVirguleIdentifierStarInBlock','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',178),
  ('EventIdentifierInBlock -> IDENTIFIER','EventIdentifierInBlock',1,'p_EventIdentifierInBlock','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',181),
  ('StateClause -> STATE StateIdentifier StateVirguleIdentifierStar','StateClause',3,'p_StateClause','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',185),
  ('EventVirguleIdentifierStarInClass -> empty','EventVirguleIdentifierStarInClass',1,'p_EventVirguleIdentifierStarInClass','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',188),
  ('EventVirguleIdentifierStarInClass -> VIRGULE EventIdentifierInClass EventVirguleIdentifierStarInClass','EventVirguleIdentifierStarInClass',3,'p_EventVirguleIdentifierStarInClass','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',189),
  ('StateVirguleIdentifierStar -> empty','StateVirguleIdentifierStar',1,'p_StateVirguleIdentifierStar','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',192),
  ('StateVirguleIdentifierStar -> VIRGULE StateIdentifier StateVirguleIdentifierStar','StateVirguleIdentifierStar',3,'p_StateVirguleIdentifierStar','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',193),
  ('ObserverStar -> empty','ObserverStar',1,'p_ObserverStar','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',196),
  ('ObserverClauseQuestionMark -> empty','ObserverClauseQuestionMark',1,'p_ObserverClauseQuestionMark','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',200),
  ('ObserverClauseQuestionMark -> OBSERVER ObserverStar','ObserverClauseQuestionMark',2,'p_ObserverClauseQuestionMark','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',201),
  ('InternalBlockBody -> ComposedBlockClause EventClauseInBlock SynchronizationClause ObserverClauseQuestionMark','InternalBlockBody',4,'p_InternalBlockBody','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',204),
  ('BasicBlockBody -> StateClause EventClauseInClass TransitionClause ObserverClauseQuestionMark','BasicBlockBody',4,'p_BasicBlockBody','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',208),
  ('BlockBody -> BasicBlockBody','BlockBody',1,'p_BlockBody','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',212),
  ('BlockBody -> InternalBlockBody','BlockBody',1,'p_BlockBody','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',213),
  ('EndBlock -> END','EndBlock',1,'p_EndBlock','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',217),
  ('EndClass -> END','EndClass',1,'p_EndClass','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',231),
  ('Class -> CLASS ClassIdentifier BlockBody EndClass','Class',4,'p_Class','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',259),
  ('Block -> BLOCK BlockIdentifier BlockBody EndBlock','Block',4,'p_Block','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',263),
  ('Model -> Block Model','Model',2,'p_Model','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',266),
  ('Model -> Class Model','Model',2,'p_Model','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',267),
  ('Model -> empty','Model',1,'p_Model','/Users/tianqilei/PycharmProjects/TSLM/lexer_parser/parser.py',268),
]
